version: "3.8"

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0   
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
  
  telemetry:
    build: ./Telemetry
    container_name: telemtry
    depends_on: 
      - mosquitto
  
  netflow:
    build: ./NetFlow
    container_name: netflow
    depends_on: 
      - mosquitto
  
  correlation:
    build: ./Correlation
    container_name: correlation
    depends_on: 
      - mosquitto