FROM kalilinux/kali-rolling
COPY ./scripts/ /home/scripts/
RUN mkdir /home/wiresharkTraces
RUN mkdir /home/logs
RUN apt-get update
RUN apt-get install hping3 -y
RUN apt-get install traceroute -y
RUN apt-get install slowhttptest -y
RUN apt-get install moreutils -y
RUN apt-get install tshark -y
RUN apt-get install cron -y
RUN echo "45 9 8 3 * root cd /home/scripts && ./attack_procedure_testing.sh" >> /etc/crontab
RUN chmod +x /home/scripts/attack_procedure_testing.sh
RUN chmod +x /home/scripts/attack.sh
RUN chmod +x /home/scripts/variables.sh
CMD ["cron", "-f"]