### TO NOT GET TCP RST run this in the host: iptables -I DOCKER-USER -i <interface of host machine> -d 172.17.0.2 -p tcp --tcp-flags RST RST -j DROP
FROM kalilinux/kali-rolling
COPY ./scripts/ /home/scripts/
RUN mkdir /home/wiresharkTraces
RUN mkdir /home/logs
RUN apt-get update
RUN apt-get install hping3 -y
RUN apt-get install traceroute -y
RUN apt-get install slowhttptest -y
RUN apt-get install moreutils -y
RUN apt-get install tshark -y
RUN apt-get install cron -y
RUN echo "20 10 7 3 * root cd /home/scripts && ./attack_procedure_testing.sh" >> /etc/crontab
RUN chmod +x /home/scripts/attack_procedure_testing.sh
RUN chmod +x /home/scripts/attack.sh
RUN chmod +x /home/scripts/variables.sh
CMD ["cron", "-f"]