FROM httpd:2.2
RUN mkdir /home/output
RUN mkdir /home/output/wiresharkTraces
RUN apt-get install iproute2 
COPY ./html/ /usr/local/apache2/htdocs/
COPY ./scripts/ /home/
RUN chmod +x /home/capture.sh
RUN chmod +x /home/variables.sh
RUN cd /home