FROM debian:stable-slim
RUN mkdir /home/output
RUN mkdir /home/output/wiresharkTraces
RUN mkdir /home/output/logs
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y hping3 traceroute slowhttptest moreutils iptables iproute2 curl procps
#ARG SSH_PRIVATE_KEY
#RUN mkdir /root/.ssh
#RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa
#RUN chmod 600 /root/.ssh/id_rsa
#ARG SSH_KNOWN_HOSTS
#RUN echo "${SSH_KNOWN_HOSTS}" >> /root/.ssh/known_hosts
COPY ./scripts/ /home/scripts/
RUN chmod +x /home/scripts/attack_procedure_testing.sh
RUN chmod +x /home/scripts/attack.sh
RUN chmod +x /home/scripts/variables.sh
RUN chmod +x /home/scripts/attack_starter.sh
RUN chmod +x /home/scripts/two_attacks.sh
RUN chmod +x /home/scripts/all_attacks.sh
RUN chmod +x /home/scripts/capture.sh