FROM httpd:2.4
COPY ./html/ /usr/local/apache2/htdocs/
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./scripts/ /home/
RUN mkdir /home/wiresharkTraces
RUN apt-get update
RUN apt-get install tshark -y
RUN apt-get install cron -y
RUN echo "35 11 6 3 * root cd /home && ./capture.sh" >> /etc/crontab
RUN chmod +x /home/capture.sh
RUN chmod +x /home/variables.sh