### TO NOT GET TCP RST run this in the host: iptables -I DOCKER-USER -i <interface of host machine> -d 172.17.0.2 -p tcp --tcp-flags RST RST -j DROP
FROM debian:stable-slim
RUN mkdir /home/wiresharkTraces
RUN mkdir /home/logs
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y hping3 traceroute slowhttptest moreutils tshark iptables iproute2 openssh-client curl
ARG SSH_PRIVATE_KEY
RUN mkdir /root/.ssh
RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
ARG SSH_KNOWN_HOSTS
RUN echo "${SSH_KNOWN_HOSTS}" >> /root/.ssh/known_hosts
COPY ./scripts/ /home/scripts/
RUN chmod +x /home/scripts/attack_procedure_training.sh
RUN chmod +x /home/scripts/attack.sh
RUN chmod +x /home/scripts/variables.sh
RUN chmod +x /home/scripts/capture.sh