FROM debian:stable-slim
RUN mkdir /home/wiresharkTraces
RUN mkdir /home/logs
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y hping3 traceroute slowhttptest moreutils tshark iptables iproute2
COPY ./scripts/ /home/scripts/
RUN chmod +x /home/scripts/attack_procedure_testing.sh
RUN chmod +x /home/scripts/attack.sh
RUN chmod +x /home/scripts/variables.sh
RUN chmod +x /home/scripts/mul_attacks.sh
RUN chmod +x /home/scripts/capture.sh