### TO NOT GET TCP RST run this in the host: iptables -I DOCKER-USER -i <interface of host machine> -d 172.17.0.2 -p tcp --tcp-flags RST RST -j DROP
FROM debian:stable-slim
RUN mkdir /home/wiresharkTraces
RUN mkdir /home/logs
RUN apt-get update
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y hping3 traceroute slowhttptest tshark cron iptables iproute2
RUN echo "45 9 8 3 * root cd /home/scripts && ./attack_procedure_training.sh" >> /etc/crontab
COPY ./scripts/ /home/scripts/
RUN chmod +x /home/scripts/attack_procedure_training.sh
RUN chmod +x /home/scripts/attack.sh
RUN chmod +x /home/scripts/variables.sh
RUN chmod +x /home/scripts/capture.sh
CMD ["cron", "-f"]